CREATE TABLE time_deposits
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_type VARCHAR(50)    NOT NULL,
    days      INTEGER        NOT NULL,
    balance   DECIMAL(19, 2) NOT NULL
);

CREATE TABLE withdrawals
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_deposit_id INTEGER        NOT NULL REFERENCES time_deposits (id),
    amount          DECIMAL(19, 2) NOT NULL,
    date            DATE           NOT NULL
);

CREATE INDEX idx_withdrawals_time_deposit_id ON withdrawals (time_deposit_id);
